export default interface iYourpayLoginObject {
  LoginID?: number,
  customer_cvr?: number,
  merchantid?: number,
  active?: number,
  username?: string,
  upassword?: string,
  pincode?: string,
  uemail?: string,
  name?: string,
  logo?: string,
  mobile?: string,
  twofactor?: number,
  session_id?: string,
  session_lastused?: number,
  user_img?: string,
  latestlogin?: number,
  logintype?: string,
  clicklink?: string,
  terminal_pwd?: string,
  stdpwd?: number,
  verified?: number,
  added_to_mailchimp?: number,
  language_code?: string,
  reset_token?: string,
  row_last_updated?: Date
}