export default interface iYourpayPSPObject {
  pspid: number,
  name: string,
  pipedrive_id: number,
  amount_of_merchants: number,
  response: string,
  settlement_days: number,
  merchant_percentage: number,
  finders_fee: number,
  finders_fee_currency: number,
  percentage: number,
  volume_total: number,
  kickback_total: number,
  kickback_released: number,
  last_updated: number,
  merchants: number,
  total_volume: number,
  total_kickback: number,
  total_release: number,
}